version: "3.9"

services:
  user-service:
    build: ./user-service
    ports:
      - "3001:3001"
    networks:
      - micro-net

  order-service:
    build: ./order-service
    ports:
      - "3002:3002"
    networks:
      - micro-net
    depends_on:
      - user-service

networks:
  micro-net:
    driver: bridge